server.port=8000

# Enable Java 21 Virtual Threads in Spring Boot
spring.threads.virtual.enabled=true

# Piped Template Engine Configurations
piped.template.prefix=src/main/resources/pte-templates
piped.template.suffix=.pte

# RecordMaster Database Configuration
recordmaster.db.path=database/taskmaster_rm
